### ISSUE TITLE
Checklist for Bioconductor submission

### ISSUE THREAD

**Issue by csoneson** [fmicompbio/TabulaMurisSenisData#3]
- [x] Add dropbox link to compiled html files to README
- [x] Upload data to AWS (contact Lori)
- [x] Expand a bit on the examples in the vignette - show e.g. UMAP/PCA and link to the official Tabula Muris Senis page for comparison
- [x] Run through and test that all (288) data object seem to be correct
- [x] Test accessor functions once the data is in the hub
- [x] Link to the Tabula Muris Senis project in the README
- [x] Add a plot example in the README
- [x] Add documentation for the data sets
- [x] Include the color vector from the consortium in the vignette

**Comment by csoneson** [comment]
And an iSEE instance? :) (although not required for submission)

**Comment by federicomarini** [comment]
Not required, but quite desired.
Also a non-insignificant case for stress load of the app, I would say.

**Comment by federicomarini** [comment]
... with which I would then say we are even entitled of being listed as "official partners" of the CZI BioHub software collection (I'll pick up on the link later)

**Comment by federicomarini** [comment]
iSEE short setup is also done, guess we can safely close this and go go go for submission!

**Comment by csoneson** [comment]
Submitted! I'll close this now :)
